### ISSUE TITLE
nice work!

### ISSUE THREAD

**Issue by yawetse** [GerkinDev/typedoc-plugin-tutorials#5]
thanks @GerkinDev for the great plugin, is it still under active development?

**Comment by GerkinDev** [comment]
Hi ! This plugin is not really under *active* development, but it is, as far as I can tell, functional.

I did not released it yet, mainly because Typedoc itself has a huge refactor pending. So I don't want to  publish a version just to be urged by a Typedoc major update  that would certainly break everything.

Anyway, are you in need of something ?

Cheers :beers:

**Comment by yawetse** [comment]
I was looking for a way to generate additional documentation with markdown and typedoc but I found another solution to generate html gracefully.

Thanks for the speedy response
